version: '2.1'

services:
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
#    below line shows how to change charset and collation
#    uncomment it if necessary
#    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vjio2fZsfe
      MYSQL_DATABASE: nc
      MYSQL_USER: noco
      MYSQL_PASSWORD: ahvG6fxmw
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    ports:
      - 3306:3306

  nocodb:
    depends_on:
      db:
        condition: service_healthy
    image: nocodb/nocodb:latest
    ports:
      - 80:80
    restart: always
    volumes:
      - nc_data:/usr/app/data
    environment:
      NC_DB: "mysql2://db:3306?u=noco&p=ahvG6fxmw&d=nc"
      NC_ADMIN_EMAIL: "admin@fenglu.vip"
      NC_ADMIN_PASSWORD: "13yws@WvnX"
      PORT: 80
volumes:
  db_data: {}
  nc_data: {}